# Generated by Django 2.1 on 2018-08-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_url', models.CharField(max_length=500)),
                ('news_title', models.CharField(max_length=500)),
                ('news_body', models.CharField(max_length=500)),
            ],
        ),
    ]
