# Generated by Django 2.1 on 2018-08-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0002_news_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=500)),
                ('category_name', models.CharField(max_length=500)),
            ],
        ),
    ]
