# Generated by Django 2.1 on 2018-08-19 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_date',
            field=models.CharField(default='SOME_STRING', max_length=500),
        ),
    ]
