# Generated by Django 2.1 on 2018-08-20 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0005_auto_20180820_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
