# Generated by Django 2.1 on 2018-08-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0006_auto_20180820_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSSLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-news_date']},
        ),
    ]
