# Generated by Django 2.1 on 2018-08-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0007_auto_20180821_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsslinks2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rsslinks3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rsslinks4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Rsslinks5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='RSSLinks',
            new_name='Rsslinks1',
        ),
        migrations.AddField(
            model_name='category',
            name='category_db',
            field=models.CharField(default='Rsslinks', max_length=500),
        ),
    ]
