# Generated by Django 2.1 on 2018-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0008_auto_20180821_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_rsslink',
            field=models.CharField(default='SOME_STRING', max_length=500),
        ),
        migrations.AddField(
            model_name='news',
            name='news_score',
            field=models.FloatField(default=0),
        ),
    ]
