# Generated by Django 2.1 on 2018-08-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0009_auto_20180821_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_db',
        ),
        migrations.AddField(
            model_name='category',
            name='category_db_id',
            field=models.IntegerField(default=0),
        ),
    ]
