# Generated by Django 2.1 on 2018-08-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0010_auto_20180821_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_db_id',
        ),
    ]
