# Generated by Django 2.1 on 2018-08-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0011_remove_category_category_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_rank',
            field=models.IntegerField(default=0),
        ),
    ]
