# Generated by Django 2.1 on 2018-08-22 11:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0013_remove_news_news_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
