# Generated by Django 2.1 on 2018-08-22 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0014_news_news_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_img_url',
            field=models.CharField(default='SOME_STRING', max_length=500),
        ),
    ]
