# Generated by Django 2.1 on 2018-08-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0015_auto_20180822_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(default=0)),
                ('country_name', models.CharField(default='SOME_STRING', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsslinks1',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsslinks2',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsslinks3',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsslinks4',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsslinks5',
            name='country_id',
            field=models.IntegerField(default=0),
        ),
    ]
