# Generated by Django 2.1 on 2018-08-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0016_auto_20180823_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_id', models.IntegerField(default=0)),
                ('cluster_rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=500)),
                ('news_url', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='news_cluster_id',
            field=models.IntegerField(default=0),
        ),
    ]
