# Generated by Django 2.1 on 2018-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0018_auto_20180824_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_country_id',
            field=models.IntegerField(default=0),
        ),
    ]
