# Generated by Django 2.1 on 2018-08-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0019_cluster_cluster_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_summary',
            field=models.CharField(default='summary is ...', max_length=2000),
        ),
    ]
