# Generated by Django 2.1 on 2018-08-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0020_news_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rsslinks6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
                ('country_id', models.IntegerField(default=0)),
                ('org_name', models.CharField(default='news_org', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Rsslinks7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rss_link', models.CharField(max_length=500)),
                ('link_rank', models.IntegerField(default=0)),
                ('country_id', models.IntegerField(default=0)),
                ('org_name', models.CharField(default='news_org', max_length=500)),
            ],
        ),
    ]
