# Generated by Django 2.1 on 2018-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0022_auto_20180825_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='cluster_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
