# Generated by Django 2.1 on 2018-08-26 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0023_cluster_cluster_category_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cluster',
            options={'ordering': ['cluster_rank']},
        ),
    ]
