# Generated by Django 2.1 on 2018-08-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0024_auto_20180826_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cached_Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=500)),
                ('keyword_country_id', models.IntegerField(default=0)),
            ],
        ),
    ]
