# Generated by Django 2.1 on 2018-08-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0025_cached_keyword'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='keyword',
            unique_together={('keyword_name', 'news_url')},
        ),
    ]
