# Generated by Django 2.1 on 2018-08-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0027_auto_20180828_0700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cached_keyword',
            unique_together={('keyword_name', 'keyword_country_id')},
        ),
    ]
