# Generated by Django 2.1 on 2018-08-30 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0028_auto_20180828_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.IntegerField(default=0)),
            ],
        ),
    ]
