# Generated by Django 2.1 on 2018-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_news', '0029_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ip_address',
            field=models.CharField(default='some_ip', max_length=2000),
        ),
    ]
